VOH substraction feature added
vanttec/vanttec_usv pull request #26
Opened 2020-09-28 03:19 UTC by vSebas

2020-09-28 23:01 UTC, ivanacollg requested changes

2020-09-28 23:01 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +    vel_th_x = speed_th * sin(obstacle_theta);
Usar structs

2020-09-28 23:01 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +    VOH.clear();
Incluir vertices en Cono C, borrar VOH

2020-10-03 15:41 UTC, vSebas commented on usv_control/src/velocity_obstacle.cpp
> +    VOH.clear();
Done

2020-10-03 16:09 UTC, vSebas commented on usv_control/src/velocity_obstacle.cpp
> +    vel_th_x = speed_th * sin(obstacle_theta);
Done

2020-10-04 00:01 UTC, merged