Feature/velocity obstacle/cone
vanttec/vanttec_usv pull request #27
Opened 2020-10-14 18:40 UTC by ianyan11

2020-10-17 01:20 UTC, ivanacollg requested changes
Comentarios general, avsame cuendo acabes para volver a checarlo

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
Quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +
Quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +ros::Publisher marker_pub;
Este es un parametro global y necesita acabar con guin bajo al final.

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +
quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +
quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +void coneDraw(Polygon_2 C){
Las funciones que no son parte de una clase se escriben en minusculas con guion bajo entre palabras

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +
quitar este espacio

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +  marker_pub = vo_node.advertise<visualization_msgs::Marker>("/usv_control/cone", 10);
Esto se tienen que inizializar en la funcion inicializar, checa la funcion y sigue el formato de los otros publishers porfa

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +  ros::Rate loop_rate(500);
loop rate = 100 porfa 500 es mucho

2020-10-17 01:20 UTC, ivanacollg commented on usv_control/src/velocity_obstacle.cpp
> +  marker.header.frame_id = "/world";
Este nombre que sea un parametro global porfavor para que sea facil de cambiar

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +ros::Publisher marker_pub;
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +void coneDraw(Polygon_2 C){
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +
Done

2020-10-18 18:18 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +  marker_pub = vo_node.advertise<visualization_msgs::Marker>("/usv_control/cone", 10);
Done

2020-10-18 18:19 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +  ros::Rate loop_rate(500);
Done

2020-10-18 18:19 UTC, ianyan11 commented on usv_control/src/velocity_obstacle.cpp
> +  marker.header.frame_id = "/world";
Done

2020-10-21 22:22 UTC, merged